[tool.poetry]
name = "positionmanager"
version = "0.1.3"
description = ""
authors = [
  "forstmeier <john.forstmeier@gmail.com>",
  "chrisaddy <chris.william.addy@gmail.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pocketsizefund = "^0.1.1"
sentry-sdk = "^2.6.0"
loguru = "^0.7.2"
aiokafka = "^0.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
