apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newsfeed
  template:
    metadata:
      labels:
        app: newsfeed
    spec:
      containers:
      - name: newsfeed
        image: pocketsizefund/newsfeed:0.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: platform
              key: sentry_dsn
        - name: EDGAR_USER_AGENT
          valueFrom:
            secretKeyRef:
              name: platform
              key: edgar_user_agent
        - name: UPSTASH_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: upstash_endpoint
        - name: UPSTASH_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: upstash_username
        - name: UPSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: upstash_password
        - name: CLAUDE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: claude_api_key
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
