[package]
name = "edgar"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
actix-web = "4.3.1"
reqwest = "0.12.4"
serde = "1.0.203"
serde_json = "1.0.117"
sqlx = "0.7.4"
tokio = "1.26.0"
