[package]
name = "discord"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
pretty_env_logger = "0.5.0"
rdkafka = { version = "0.36.2", features = ["sasl", "ssl", "ssl-vendored"] }
sentry = "0.34.0"
serde = "1.0.203"
serde_json = "1.0.117"
serenity = "0.12.2"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.8.0", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"

[dev-dependencies]
testcontainers = "0.18.0"
testcontainers-modules = { version = "0.6.1", features = ["kafka"] }

