name: Python CI

on:
  pull_request:
    types: [opened, synchronize, closed, reopened]

jobs:
  run_unit_tests:
    name: Run Python unit tests for pocketsizefund library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: setup mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
      - name: Run unit tests
        run: mise run pkg:test
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.xml

  run_lint:
    name: Run Python lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: setup mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Run lint
        run: mise run lint:python

  run_dead_code:
    name: Run Python dead code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: setup mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Run dead code
        run: mise run check:dead-code

  publish_package:
    name: Publish Python package to PyPI
    runs-on: ubuntu-latest
    needs: [run_unit_tests, run_lint, run_dead_code]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: setup mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
      - name: Run dead code
        run: mise run pkg:publish
