name: Python CI
on:
  pull_request:
    types: [opened, synchronize, closed, reopened]
env:
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  AWS_DEFAULT_REGION: us-east-1
jobs:
  run_unit_tests:
    name: Run Python unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Setup application
        run: make setup
      - name: Run unit tests
        run: make python-unit-test
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.xml
  run_lint:
    name: Run Python lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Setup application
        run: make setup
      - name: Run lint
        run: make python-lint
  run_dead_code:
    name: Run Python dead code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Setup application
        run: make setup
      - name: Run dead code
        run: make python-dead-code
